### ISSUE TITLE
Isolines running out of memory

### ISSUE THREAD

**Issue by mimre-anl** [RaumZeit/MarchingSquares.js#17]
Hi,

I've been running into some cases where isolines runs out of memory, due to the fact that x keeps growing (bigger than 'rows') and never decreases in line 645 of marchingsquares-esm.js

`           

                  if ((typeof cellGrid[x] === 'undefined') ||

                  (typeof cellGrid[x][y] === 'undefined')) {

                  if (((dir === 0) && (y < 0)) ||

                      ((dir === 1) && (x < 0)) ||

                      ((dir === 2) && (y === rows)) ||

                      ((dir === 3) && (x === rows))) {

                    x -= add_x[dir];

                    y -= add_y[dir];

                    dir = (dir + 1) % 4;

                    count++;
                  }
                }`

In that part, x keeps growing bigger than rows (i guess the step where x === rows happens doesn't coincide with dir === 3).

For now I changed it to x >= rows, and y >= rows.

I'm not quite sure why this happens, just wanted to report it.

**Comment by RaumZeit** [comment]
Thanks for the bug report!
The check should have actually been `x===cols` and `y===rows`! You wouldn't see any weird behavior as long as the input grid is a square, i.e. `rows === cols`, but you seem to have passed a rectangle...
I just committed a fix (9cb922e1cd60f77c5f38f4cbcba4caeaa53db844) and will prepare a bugfix release as soon as possible.
*Sorry for the inconvenience*

**Comment by mimre-anl** [comment]
works like a charm!
Thank you for the quick reply
