### ISSUE TITLE
Why isoline with boundary box?

### ISSUE THREAD

**Issue by IMMSPgisgroup** [RaumZeit/MarchingSquares.js#19]
In version 1.3.2 we use MarchingSquaresJS.isoContours().
If options.linearRing = false; then 
[scratchpadMarchingSquaresJS132_02.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2364680/scratchpadMarchingSquaresJS132_02.zip).
If options.linearRing = true; then 
[scratchpadMarchingSquaresJS132_01.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2364682/scratchpadMarchingSquaresJS132_01.zip). In this case we see isoline with boundary box, but without one edge.
Another example.
If options.linearRing = false; then 
[scratchpadMarchingSquaresJS132_03.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2364695/scratchpadMarchingSquaresJS132_03.zip) without boundary box.
If options.linearRing = true; then 
[scratchpadMarchingSquaresJS132_04.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2364696/scratchpadMarchingSquaresJS132_04.zip) with boundary box.
How we can get only isoline, without boundary box?
May be, we have to use some options of MarchingSquaresJS.isoContours()? What options and how?
What we do wrong?

**Comment by RaumZeit** [comment]
With `options.linearRing = true` all paths MUST be closing a polygon by definition. Furthermore, the definition states, that first and last coordinate must be identical!
Thus, isolines that leave the data grid MUST have a boundary box. Again, by definition!

**Comment by programmingprincess** [comment]
So is there a way to not draw the outer boundary box? @IMMSPgisgroup did you find a way?
