### ISSUE TITLE
Overlapping bands

### ISSUE THREAD

**Issue by stebogit** [RaumZeit/MarchingSquares.js#2]
Hello @RaumZeit ,
I am using your `marchingsquares-isobands.js` library to basically draw a heatmap on a Google Map.
My solution works quite ok, and the isolines are always correct; however some times the heatmap shows few overlapping (see attachment), like the `marchingsquares` algorithm misses to "subtract" a region from some isoband.
Unfortunately I couldn't relate the problem to anything in particular.

Would you mind taking a look to your code and see if you can identify any issue?
Thanks
cc @pkerpedjiev 

![issue](https://cloud.githubusercontent.com/assets/12717225/16000372/d1caafc2-3100-11e6-8ffb-2b40bb7f6c74.png)

**Comment by RaumZeit** [comment]
Hi Stefano,
sorry for the late reply. Can you provide me with this example of yours (or a reduced example that also shows this issue? I think it is much easier if I have access to a data set where this particular error appears.
Thanks

**Comment by stebogit** [comment]
Hi Ronny,
thanks for your reply.
I managed to solve the issue, which apparently is related to the final composition of the bands. It seems in fact that if you directly convert the array of `GeoJSON` `LineRing`s provided by your algorithm into (Multy) `Polygons` you sometimes get the overlapping. This is because a `MultiPolygon` expects to have the larger/external `LineRing` as the first `Polygon` of the array, and all the following ones are considered internal to that.
To fix the issue I take the coordinates provided by your algorithm, convert them into `Polygons`, order them decreasingly by area, and, starting from the top, divide them into groups, being the first of each group the outermost `Polygon` of the group. 
I used [TurfJs](https://github.com/turfjs/turf/) to process the data.

This solution is a bit clunky I believe, do you think it would be possible for you to adjust the outcome of your `IsoBands` function?
To be honest I (stupidly) have never check your `IsoContours` functions, it might do what I needed...

I also (somehow, probably badly) dismembered your code so I could import in my code just the function I needed as an npm module. It might be a good option for your library.

Thanks
