### ISSUE TITLE
With options.linearRing = true 4 parts in isoline but if options.linearRing = false 84 part. 

### ISSUE THREAD

**Issue by IMMSPgisgroup** [RaumZeit/MarchingSquares.js#20]
![scratchpadmarchingsquaresjs132_07](https://user-images.githubusercontent.com/33963849/45601344-1a68fb00-ba14-11e8-9e76-91b2ed255de2.jpg)
![scratchpadmarchingsquaresjs132_06](https://user-images.githubusercontent.com/33963849/45601345-1a68fb00-ba14-11e8-8873-02266bebc628.jpg)

With options.linearRing = true 4 parts in isoline but if options.linearRing = false 84 part. 
But in this isoline must be four parts.
This is in version 1.3.2.
First picture if options.linearRing = true.
Some examples.
[scratchpadMarchingSquaresJS132_0708.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2387064/scratchpadMarchingSquaresJS132_0708.zip)

**Comment by RaumZeit** [comment]
I've already explained the reasons before in https://github.com/RaumZeit/MarchingSquares.js/issues/18

You are welcome to patch the polygon/path tracing algorithm to solve this issue...

**Comment by IMMSPgisgroup** [comment]
You speak about this bag? We thinked that this bug fixed in version 1.3.2 :). We try to make path tracing algoritms with hashed dictionaties of segements and points. This work not bad, may be slowly ... in simple case when in one points only two points may touch :(. We do not have many time for investigations about this :(. We use version 1.2.1 beacause it give _correct in looks isoline_ maybe in all case. We use that for curvililinear grid with convex quadrilaterals (i.e. phisical and computational space), of course, after transformations.
We think if linearRing = false  that so we take in result isoline without boundary box. We mistaked? We see boundary box without isoline " _a grin without a cat!_" :).
[linearRingFalseOnlyBoundaryBoxWithoutEdge.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2499596/linearRingFalseOnlyBoundaryBoxWithoutEdge.zip)
[map2.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2499619/map2.zip)
![map2](https://user-images.githubusercontent.com/33963849/47272541-eabb8e80-d58f-11e8-8321-8fca49e50f09.jpg)
What are we doing wrong?
This is really _complex isoline_.
[complexlsoline.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2499599/complexlsoline.zip)
[map.zip](https://github.com/RaumZeit/MarchingSquares.js/files/2499602/map.zip)
![map](https://user-images.githubusercontent.com/33963849/47272637-21de6f80-d591-11e8-9bf2-3474465a76cd.jpg)
This is maybe correct in version 1.3.2 :).
______________________________________________________________________________________________________
With best regards, IMMSPgisgroup
