### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by landswellsong** [RaumZeit/MarchingSquares.js#22]
Hi,
We've used your package at `1.2.0` version in our project and now that I'm rebuilding our code it crashes. I tracked it down to `1.3.2` being pulled in instead and apparently the code isn't drop-in compatible. Our `package.json` lists the dependency as `^1.2.0` which is supposedly meant to be "compatible with". Of course I'll just set the exact version now and afterwards port to your newer releases when I have time, but I was just curious why it happens.

Could you please clarify the situation here or fix it so that `1.3.2` isn't marked as `1.2.0` compatible? 

Maybe I'm missing something because I'm totally not a JS person.

PS: thanks for the package

**Comment by RaumZeit** [comment]
Late answer but still an answer ;)

I just took a look at the problem you've been faced with. It seemed that transitioning to ES6 modules in version 1.3 of MarchingSquaresJS required a minor change in how you import the module.

I've prepared a PR that should solve your problem.

See https://github.com/IonosatMicro/promis/pull/302

**Comment by gloriajjl** [comment]
хм, якщо я правильно зрозуміла суть цією різниці в синтаксисі, яку можна знайти в цьому пул реквесті, то вона полягає в наступному. Модулі можуть мати пений набір функцій чи об'єктів визначених всередині себе. Ті з них, які мають бути доступні при імпорті модуля, позначені ключовим словом експорт. А деякі з них ще додатково можуть бути позначені ключовим словом дефолт.
Коли ми робимо "імпорт * as шототам фром шототам", то получаємо всі ці експорти в своє розпорядження. А коли "імпорт шототам фром шототам", то получаємо тільки ті ескорти, які були також позначені дефолт.
