### ISSUE TITLE
How to generate data based on image?

### ISSUE THREAD

**Issue by msurguy** [RaumZeit/MarchingSquares.js#24]
Hello and thank you so much for releasing this JS library and examples! 

I was wondering how the vienna_basin data was generated based on the PNG image: https://github.com/RaumZeit/MarchingSquares.js/tree/master/examples/vienna

Could you please provide some information on how I can do that with my own images? 

Thank you!

**Comment by RaumZeit** [comment]
I did use Python `PIL.Image` and `numpy` to convert the grayscale image to an 8-bit array:
```.py
from PIL import Image
import numpy as np
import sys

im = Image.open("vienna_basin.png")
arr = np.array(im)

sys.stdout.write("[\n")
for j in range(0, arr.shape[0]):
    sys.stdout.write("  [")
    for i in range(0, arr.shape[1]):
        if i < arr.shape[1] - 1:
            sys.stdout.write("%d, " % arr[i,j][0])
        else:
            sys.stdout.write("%d" % arr[i,j][0])
    if j < arr.shape[0] - 1:
        sys.stdout.write("],\n")
    else:
        sys.stdout.write("]\n")
sys.stdout.write("]\n")

```
