### ISSUE TITLE
progressCallback

### ISSUE THREAD

**Issue by stebogit** [RaumZeit/MarchingSquares.js#4]
@RaumZeit 
it seems to me the `progressCallback` is never called.
I set up [this fiddle](https://jsfiddle.net/jStefano/vbekv9qe/) using Peter Kerpedjiev's snippet as an example.

**Comment by RaumZeit** [comment]
Uhh, yes. You are totally right... This callback is never called at all. We can remove it for now. I think I remember that I wanted t implement something in this direction but never got to it...

**Comment by RaumZeit** [comment]
ProgressCallback is removed in latest commit
