### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by stebogit** [RaumZeit/MarchingSquares.js#6]
@RaumZeit I find the result of [this example](https://jsfiddle.net/jStefano/tu1dnsy3/) quite unexpected, if not wrong.
Setting `zs = [0, 3]`, when the lowest value in the matrix is 1, `MarchingSquares` returns only the isoline equal to 3.
I would expect always two isolines as MS output, in this case with one isoline being the outer boundary of the matrix. Otherwise how do you know if the values between 0 and 3, in this case, are inside or outside the single isoline? 
Am I right?

Also, there is another issue with this example.
If you set `zs = [3, 5]` the output looks like this (wrong):
![screen shot 2017-04-27 at 1 19 50 am](https://cloud.githubusercontent.com/assets/12717225/25474559/863f4e54-2ae8-11e7-8044-42407d468bd0.png)
while if you set `zs = [5, 7]` the output is this (correct):
![screen shot 2017-04-27 at 1 26 04 am](https://cloud.githubusercontent.com/assets/12717225/25474575/908328f4-2ae8-11e7-9d52-5e88c1fadd14.png)
 
What do you think? Am I missing something here?
Thanks

**Comment by stebogit** [comment]
@RaumZeit modifying the matrix breaking the outer circle of 1s the output of `zs = [0, 3]` is correct:
![screen shot 2017-04-27 at 1 34 18 am](https://cloud.githubusercontent.com/assets/12717225/25474986/191ddc62-2aea-11e7-82af-e817f5a71a15.png)

but not with `zs = [3, 5]` (the inner isoline is still misshaped):
![screen shot 2017-04-27 at 1 41 41 am](https://cloud.githubusercontent.com/assets/12717225/25475238/effe80ce-2aea-11e7-91f7-40a8e577d0a7.png)

**Comment by RaumZeit** [comment]
I'm already looking into this issue. Something seems bogus in the routine that attempts to close polygons next to missing data and the edges of the grid. I'll come back to you as soon as I have a fix for that...

**Comment by stebogit** [comment]
@RaumZeit great thanks!
Since you're looking into this, two notes:
- I recently verified that the input needs to be flipped upside-down to have the right output, i.e. the MS output is reversed than what expected; is that done on purpose for some reason?
- The main issue I had (and still I'm not sure it's 100% reliable) implementing `@turf/isobands` was having the `LinearRings` (i.e. output of MS) composing the `Polygons` all properly nested in order to meet the [GeoJson specs](https://tools.ietf.org/html/rfc7946#section-3.1.6) (which Google Maps for example is pretty strict in implementing):

   >For Polygons with more than one of these rings, the first MUST be the exterior ring, and any others MUST be interior rings. The exterior ring bounds the surface, and the interior rings (if present) bound holes within the surface.

   Would it be possibile/easy for you to address that issue directly inside MS? I was wondering if that could actually be easily achieved simply tweaking your routine and make the overall script much faster.

Thanks!

**Comment by RaumZeit** [comment]
So, I've been looking into the issue and it seems a little more complex than I thought. I think just fixing the polygon merge step will require a little time. I cam up with a smaller grid that already shows errors and fixing some of the steps break things at other sites. I hope that I'll find some more time next weekend to finally come up with the fix.

Regarding your last post:
- I don't know what you mean by flipped upside-down. With an input like
```javascript
    var data = [
        [ 1, 1],
        [ 1, 5 ]
      ];
```
the output looks ok to me. Note, the triangle part is located in the bottom right part of the SVG as expected. Afterall, its x-y coordinates are the largest and SVG coordinate system has its origin in upper-left corner, if I'm not mistaken

- I see your point, and also I'd really like to address this already in the MS code. However, this will require some clever method while tracing back the _full_ polygons. Right now, each cell in the MS grid is used as a potential starting point for a polygon trace. Whether it is an _inner_ (defining holes) or an _outer_ (defining the entire area) trace is not known at this moment. Also, I'm not entirely sure, but right now, all traces should be in counter-clockwise orientation. Reverting to the _atomic_ MS squares as returned polygons, i.e. setting
```javascript
polygons = true
```
in the options object would circumvent the GeoJSON RFC problem for now, though with the drawback of extremely large numbers of polygons.

I think having this done already in the MS code should be part of a new milestone for a new version of my library.

**Comment by stebogit** [comment]
@RaumZeit Thanks for your support.

>With an input like

``` javascript
var data = [
  [ 1, 1 ],
  [ 1, 5 ]
];
```

the actual MS output is:
```json
[
  [0.5,  1],
  [  1,0.5],
  [  1,  0],
  [  0,  0],
  [  0,  1],
  [0.5,  1]
]
```
![untitled drawing 1](https://cloud.githubusercontent.com/assets/12717225/25938843/9c8f0a66-35e5-11e7-9085-f15fcf2e6306.png)


which is upside-down compared to what you see in the [jsFiddle](https://jsfiddle.net/jStefano/tu1dnsy3/), where somehow for some reason `d3.js` tips it over back.

I currently just flip the input and it works fine, but I guess it's an unexpected behaviour.

**Comment by RaumZeit** [comment]
I think this is exactly what you would expect! The drawing you made correctly reflects the input as processed by the MS algorithm:
```
data[0][0] = 1;
data[0][1] = 1;
data[1][0] = 1;
data[1][1] = 5;
```
However, when you create the SVG image (using d3.js or anything else), the coordinate system is actually a horizontally flipped version of what the input was like. This is an implicit property of SVG images, the origin, i.e. [0,0], is at the top left corner (https://www.w3.org/TR/SVG/coords.html#InitialCoordinateSystem).

**Comment by stebogit** [comment]
You're right, it make sense now! 😃 
I would put this example/explanation in the documentation though, cause it's not immediate to get the origin is actually the first element of the array (I guess the vertical formatting of the array's elements misleaded me)

Also, I knew this, I should have thought about it 👍 
> an implicit property of SVG images, the origin, i.e. [0,0], is at the top left corner  

That's probably why it was even less intuitive to expect the origin position in the right place

**Comment by stebogit** [comment]
ping @RaumZeit 
any progress on this issue?

**Comment by RaumZeit** [comment]
@stebogit unfortunately, I did not find time to refactor the polygon closing part just yet.
I hope, I'll find some consecutive days to spend time on that matter within the next weeks

**Comment by RaumZeit** [comment]
In the last two weeks, I've been re-implementing the entire Marching Squares algorithms, both IsoContours and IsoBands. The spurious problems with strange polygons seem to have vanished, and I'm almost certain that the module now works correctly with any regular input data.

So I close this issue now, though I didn't address one of the points you brought up earlier:
_The proper nesting of the polygon paths..._
If this still poses a problem, could you please open a new issue for that?

**Comment by stebogit** [comment]
Sure @RaumZeit, I will.
Thanks for taking care of this!

BTW, I'd be happy to set up a few tests if you'd consider a PR for that.

**Comment by RaumZeit** [comment]
@stebogit Sure, feel free to submit the PR for integrating your unit tests! I'd be happy to merge them
