### ISSUE TITLE
Support ES Modules?

### ISSUE THREAD

**Issue by DenisCarriere** [RaumZeit/MarchingSquares.js#8]
@RaumZeit Any chance you could support ES Modules? 

At the moment, importing your library doesn't seem to work with CommonJS or ES Modules, it's only UMD which is only good for the browser.

TravisCI error bundling TurfJS:
https://travis-ci.org/Turfjs/turf/jobs/280180562#L3105

If you need any help implementing this, let me know and I can send a PR with a fix, you'll just need to publish the NPM once everything is merged.

**Comment by RaumZeit** [comment]
@DenisCarriere Unfortunately, I don't know much about ESM. The only things I found were that UMD and ESM seem to be incompatible. So currently, I'm out of ideas how to provide support for all the different ways how to include the module (AMD, <script>, require.js, Node, and so on)
Any suggestions for how to start-off a multi-purpose module (PR, link, or whatever) are welcome!
I'd be happy to provide the ESM support as well.

**Comment by DenisCarriere** [comment]
No worries about the ESM modules, they are still a bit too "hacky" for their benefits.

**Comment by RaumZeit** [comment]
@DenisCarriere I've had a look into how to create ES2015 modules, and already started a new branch for it:
https://github.com/RaumZeit/MarchingSquares.js/tree/dev_modules
It's most likely, that this will be merged in the next release...
I didn't know about rollup.js which seems to make development with modules and distribution as UMD pretty easy ;)
